title: Mehr Anand - Portfolio
description: AI‑focused CS + Applied Math @ Northeastern · Building ML + analytics that ship
# Disable Jekyll theme to use custom site
theme: null
plugins: []
# Show downloads button
show_downloads: false
